# Глава 3 Числа, даты и время(Python Дэвид Бизли)

# Округление числовых значений

https://ru.wikipedia.org/wiki/%D0%9E%D0%BA%D1%80%D1%83%D0%B3%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5#%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D1%8B_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_0,5_%D0%BA_%D0%B1%D0%BB%D0%B8%D0%B6%D0%B0%D0%B9%D1%88%D0%B5%D0%BC%D1%83_%D1%86%D0%B5%D0%BB%D0%BE%D0%BC%D1%83

Вы хотите округлить число с плавающей точкой до заданного количества знаков после точки.

Для простого округления используйте встроенную функцию round(value, ndigits). 

In [1]:
round(1.23, 1)

1.2

In [2]:
round(1.27, 1)

1.3

In [3]:
round(-1.27, 1) 

-1.3

In [4]:
 round(-1.25361, 3) 

-1.254

Когда значение попадает точно между двух возможных выборов для округления, эта функция будет округлять к ближайшему четному значению. То есть 1.5 или 2.5 будут округлены до 2. 

In [5]:
 round(2.5, 0) 

2.0

In [6]:
 round(1.5, 0) 

2.0

In [7]:
 round(2.5) 

2

In [8]:
 round(1.5) 

2

Количество знаков, которое передается функции round(), может быть отрицательным. В этом случае округление будет идти до десятков, сотен, тысяч и т. д. 

In [11]:
 round(1521, -2) 

1500

In [12]:
a = 1627731

In [14]:
 round(a, -1) 

1627730

In [15]:
 round(a, -2) 

1627700

In [16]:
 round(a, -3) 

1628000

Не перепутайте округление с форматированием значения для вывода. Если вы хотите просто вывести число с некоторым определенным количеством знаков после точки, обычно вам не требуется round(). Вместо этого просто задайте при форматировании, сколько знаков выводить.

In [17]:
x = 1.23456 
format(x, '0.2f') 

'1.23'

In [18]:
format(x, '0.3f') 

'1.235'

In [19]:
'value is {:0.3f}'.format(x) 

'value is 1.235'

Сопротивляйтесь желанию округлить числа с плавающей точкой, чтобы исправить проблемы с точностью вычислений. 

In [22]:
a = 2.1 
b = 4.2 
c = a + b 

In [23]:
c

6.300000000000001

In [25]:
c = round(c, 2)

In [26]:
c

6.3

Для большинства программ, работающих с числами с плавающей точкой, просто не нужно (и не рекомендуется) этого делать. Хотя есть незначительные ошибки в вычислениях, поведение этих ошибок понятно и терпимо. 

 Если необходимо избежать таких ошибок (например, это может быть важно для финансовых приложений), попробуйте модуль decimal.

# Выполнение точных вычислений с десятичными дробями

Вам нужно выполнить точные вычисления с десятичными дробями, и вы хотите избавиться от небольших ошибок, которые обычно возникают при работе с числами с плавающей точкой. 

Широко известный недостаток чисел с плавающей точкой в том, что они не могут точно представить все 10 базовых десятичных цифр. Более того, даже простые математические вычисления приводят к появлению небольших ошибок. 

In [27]:
a = 4.2
b = 2.1
a + b

6.300000000000001

In [28]:
(a + b) == 6.3

False

Эти ошибки – «особенность» процессора и  стандарта представления чисел с плавающей точкой IEEE 754, на основе которого работает модуль процессора для вычислений с плавающей точкой. Поскольку в типе данных «числа с плавающей точкой» Python хранит данные, используя нативное представление, вы ничего не можете сделать, чтобы избавиться от ошибок при использовании экземпляров float. 

Если вам нужна большая точность (и вы готовы в некоторой степени поступиться производительностью), то можете использовать модуль decimal: 

In [29]:
from decimal import Decimal

In [30]:
a = Decimal('4.2')
b = Decimal('2.1')

In [31]:
a + b

Decimal('6.3')

In [32]:
print(a + b)

6.3


In [33]:
(a + b) == Decimal('6.3')

True

На первый взгляд он может показаться странным (например, определение чисел как строк). Однако объекты Decimal работают именно так, как вы можете ожидать (поддерживают все обычные математические операции и т. д.). Если вы выводите их или используете в функциях форматирования строк, они выглядят как обычные числа. 

Главное преимущество decimal в том, что он позволяет контролировать различные аспекты вычислений, такие как число знаков после точки и округление. Чтобы это сделать, вы создаете локальный контекст и меняете его установки. Например: 

In [34]:
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
print(a/b)

0.7647058823529411764705882353


In [35]:
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.765


In [36]:
with localcontext() as ctx:
    ctx.prec = 50
    print(a/b)

0.76470588235294117647058823529411764705882352941176


Модуль decimal реализует «Общую спецификацию десятичной арифметики» («General Decimal Arithmetic Specification»)  компании IBM. 

Если вы работаете с научными или инженерными данными, компьютерной графикой, то вполне нормально использовать обычный тип данных чисел с плавающей точкой. В общем­то, очень немногие вещи в реальном мире измеряются с точностью до 17­го знака после точки, которую предоставляет float. Так что небольшие ошибки не так уж важны. А производительность нативных чисел с плавающей точкой заметно выше, что важно при выполнении большого количества вычислений. 

Но вы не должны просто полностью игнорировать ошибки. 

In [37]:
nums = [1.23e+18, 1, -1.23e+18] 

In [38]:
sum(nums)

0.0

Ошибка из последнего примера может быть решена путем использования math. fsum(): 

In [39]:
import math
math.fsum(nums)

1.0

Однако для других алгоритмов - придется изучить реализацию и понять, как они работают с точки зрения подобных ошибок. 

Подведем итог: модуль decimal используется в основном в финансовых и прочих подобных приложениях. В таких программах небольшие ошибки в вычислениях ужасно мешают, а decimal позволяет от них избавиться.

Также часто можно встретить объекты класса Decimal в интерфейсах Python к базам данных –  особенно часто их используют для доступа к финансовым данным. 

# Форматирование чисел для вывода

Вам нужно отформатировать число для вывода, контролируя количество знаков, выравнивание, включение разделителя для разрядов.

Чтобы отформатировать одно число для вывода, используйте встроенную функцию format(). 

In [1]:
x = 1234.56789

In [3]:
# Два десятичных знака точности 
format(x, '0.2f')

'1234.57'

In [4]:
# Выравнивание по правому краю в 10 символов, один знак точности 
format(x, '>10.1f')

'    1234.6'

In [5]:
# Выравнивание по левому краю 
format(x, '<10.1f')
    

'1234.6    '

In [6]:
# Выравнивание по центру 
format(x, '^10.1f')

'  1234.6  '

In [7]:
# Включение разделителя разрядов 
format(x,',')

'1,234.56789'

In [8]:
format(x, '0,.1f')

'1,234.6'

Если вы хотите использовать экспоненциальную нотацию, измените f на e или E (в зависимости от регистра, который вы хотите использовать для обозначения экспоненты). 

In [9]:
format(x, 'e')

'1.234568e+03'

In [10]:
format(x, '0.2E')

'1.23E+03'

Общая форма ширины и  точности в  обоих случаях такова:

'[<>^]?width[,]? (.digits)?', 

где width и digits – целые числа, а ? обозначает необязательные части. Тот же формат используется в строковом методе format(). 

In [11]:
'The value is {:0,.2f}'.format(x)

'The value is 1,234.57'

Прием,  работает и для чисел с плавающей точкой, и для экземпляров Decimal из модуля decimal. 

Когда количество знаков ограничено, значения округляются таким же образом, как и при использовании функции round(). 

In [13]:
x

1234.56789

In [14]:
format(x, '0.1f')

'1234.6'

In [15]:
format(-x, '0.1f')

'-1234.6'

Обычное форматирование значений с добавлением разделителя разрядов ничего не знает о принятых в конкретных странах традициях форматирования тысячных разрядов. Если вам нужно принять во внимание эти традиции, обратите внимание на функции модуля locale. Вы также можете заменить символ разделителя разрядов, используя строковый метод translate(). 

In [18]:
swap_separators = { ord('.'):',', ord(','): '.'}
format(x, ',').translate(swap_separators)

'1.234,56789'

В мире все еще очень много кода, использующего форматирование чисел на основе оператора %. 

In [20]:
'%0.2f'  % x

'1234.57'

In [21]:
'%10.1f'  % x

'    1234.6'

In [22]:
'%-10.1f'  % x

'1234.6    '

Это форматирование все еще приемлемо, но обладает меньшими возможностями, нежели современный метод format(). Например, форматирование с  помощью оператора % не поддерживает добавление разделителя разрядов. 

In [24]:
f'{x:0.2f}'

'1234.57'

# Работа с бинарными, восьмеричными и шестнадцатеричными целыми числами 

Вам нужно преобразовать выводимые целые числа в бинарное, восьмеричное или шестнадцатеричное представление. 

Чтобы преобразовать целое число в бинарное, восьмеричное или шестнадцатеричное представление, используйте функции bin(), oct() или hex() соответственно: 

In [25]:
x = 1234

In [26]:
bin(x)

'0b10011010010'

In [27]:
oct(x)

'0o2322'

In [29]:
hex(x)

'0x4d2'

Или вы можете использовать функцию format(), если не хотите, чтобы появлялись префиксы 0b, 0o или 0x.

In [31]:
format(x, 'b')

'10011010010'

In [33]:
format(x, 'o') 

'2322'

In [35]:
format(x, 'x') 

'4d2'

Целые числа имеют знак, поэтому если вы работаете с отрицательными значениями, то вывод также будет включать знак. 

In [37]:
x = -1234

In [39]:
format(x, 'b')

'-10011010010'

In [41]:
format(x,'x')

'-4d2'

Если вы хотите вывести значение без знака, вам нужно добавить максимальное значение, чтобы установить длину бита. Например, чтобы вывести 32-битное значение, можно поступить так: 

In [43]:
x = -1234

In [45]:
format(2**32 + x, 'b')

'11111111111111111111101100101110'

https://ds05.infourok.ru/uploads/ex/0b67/0003ef7e-25a1dd79/img22.jpg

http://900igr.net/up/datas/69375/005.jpg

In [46]:
#число с инверсией
~3

-4

In [47]:
format(2**32 + x, 'x') 

'fffffb2e'

Чтобы преобразовать строки с целыми числами в числа с разными основаниями, используйте функцию int(), указав нужное основание.

In [48]:
int('4d2', 16)

1234

In [49]:
0xff

255

In [51]:
int('10011010010', 2)

1234

По большей части работа с бинарными, восьмеричными и шестнадцатеричными целыми числами прямолинейна. Просто запомните, что эти преобразования относятся только к выводу разных текстовых представлений чисел. «Под капотом» это один и тот же тип целых чисел. Предупреждение для программистов, работающих с восьмеричными числами: синтаксис Python для определения восьмеричных значений немного отличается от реализованного в большинстве других языков. Если вы попробуете сделать это так, то получите синтаксическую ошибку: 

In [52]:
import os
os.chmod('script.py', 0755)

SyntaxError: invalid token (<ipython-input-52-7619b0e4e554>, line 2)

Убедитесь, что вы вводите восьмеричное значение с префиксом 0o, как показано тут: 

In [ ]:
import os
os.chmod('script.py', 0o755)

# Упаковка и распаковка больших целых чисел  из байтовых строк

У вас есть строка байтов, и вам нужно распаковать ее в целочисленное значение. Или же вам нужно конвертировать большое целое число в байтовую строку. 

Предположим, ваша программа должна работать с байтовой строкой из 16 элементов, которая содержит 128-битное целочисленное значение.

In [1]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

Чтобы перевести байты в целое число, используйте int.from_bytes(), определив порядок следования байтов таким образом: 

In [2]:
len(data)

16

In [3]:
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [4]:
int.from_bytes(data, 'big')

94522842520747284487117727783387188

Чтобы преобразовать большое целочисленное значение обратно в байтовую строку, используйте метод int.to_bytes(), определив количество байтов и порядок их следования. Например: 

In [5]:
x = 94522842520747284487117727783387188 

In [6]:
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [7]:
x.to_bytes(16, 'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

Преобразование больших целочисленных значений из и в байтовые строки – не самая обычная операция. Однако иногда такая задача возникает в областях типа криптографии или работы с сетью. Например, сетевые адреса IPv6 представлены 128­битными целыми числами. Если вы пишете программу, в которой нужно вытягивать такие значения из данных, то можете столкнуться с этой задачей.

В качестве альтернативы вы можете попытаться распаковывать значения, используя модуль struct, как описано в рецепте 6.11. Это работает, но размер целых чисел, которые могут быть распакованы с помощью struct, ограничен.

Структура

struct.unpack(format, data)

Распаковывает данные из структуры

In [8]:
data

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [9]:
import struct
hi, lo = struct.unpack('>QQ', data)

http://ilnurgi1.ru/docs/python/modules/struct.html

https://docs.python.org/3.8/library/struct.html

In [11]:
hi

5124093560524971

In [12]:
(hi<<64)

94522842520747284429152569981403136

In [13]:
lo

57965157801984052

In [10]:
(hi<<64) + lo

94522842520747284487117727783387188

Определение порядка следования байтов (little или big) просто указывает, записаны ли байты, из которых составляется целое число, в порядке от старшего к младшему или наоборот. Это легко понять, рассмотрев пример такого специально составленного шестнадцатеричного значения: 

In [14]:
x = 0x01020304 

In [15]:
x.to_bytes(4, 'big') 

b'\x01\x02\x03\x04'

In [16]:
x.to_bytes(4, 'little') 

b'\x04\x03\x02\x01'

Если вы хотите упаковать целое число в строку байтов, но оно не поместится, вы получите ошибку. При необходимости вы можете использовать метод int.bit_ length(), чтобы определить, сколько байтов потребуется для хранения значения:

In [17]:
x = 523 ** 23 

In [18]:
x

335381300113661875107536852714019056160355655333978849017944067

In [19]:
x.to_bytes(16, 'little') 

OverflowError: int too big to convert

In [20]:
 x.bit_length() 

208

In [21]:
#nbytes - целая часть
#rem -  остаток от деления
nbytes, rem = divmod(x.bit_length(), 8)

In [22]:
if rem:
    nbytes += 1

In [23]:
x.to_bytes(nbytes, 'little')

b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'

# Вычисления с комплексными числами

Возможно, ваша программа для взаимодействия с веб­сервисом для аутентификации последнего поколения столкнулась с сингулярностью, и ваш единственный способ обойти это лежит через комплексную плоскость... Или же вам просто нужно выполнить какие-то вычисления с использованием комплексных чисел.

Комплексные числа могут быть определены с использованием функции complex(real, imag) или добавлением окончания j к числу с плавающей точкой. Например: 

In [1]:
 a = complex(2, 4) 

In [4]:
b = 3 - 5j 

In [2]:
a

(2+4j)

In [5]:
b

(3-5j)

Реальное, мнимое и объединенное значения получить легко: 

In [6]:
a.real 

2.0

In [7]:
 a.imag 

4.0

In [8]:
#сопряженное значение
a.conjugate() 

(2-4j)

Работают все обычные математические операторы: 

In [9]:
a + b

(5-1j)

In [10]:
# (e+jf)*(c+jd) = (ec - fd) + j(fc + ed)
a * b

(26+2j)

In [11]:
# (e + jf) / (x + jy) = (e+jf)*(x-jy)/(x^2 + y^2)=
# =(ex-fy)/(x^2 + y^2) + j (ey + fx) / (x^2 + y^2)

a/b

(-0.4117647058823529+0.6470588235294118j)

In [12]:
# |x+jy| = sqrt(x^2 + y^2)
abs(a) 

4.47213595499958

Для специальных операций с комплексными числами, таких как синусы, косинусы или квадратные корни, используйте модуль cmath: 

In [13]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [14]:
cmath.cos(a)

(-11.36423470640106-24.814651485634187j)

In [15]:
cmath.exp(a) 

(-4.829809383269385-5.5920560936409816j)

Большинство связанных с математикой модулей Python умеет работать с комплексными числами. Например, если вы используете numpy, то сможете создавать массивы комплексных чисел и выполнять операции над ними: 

In [16]:
import numpy as np 
a = np.array([2+3j, 4+5j, 6-7j, 8+9j]) 
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [17]:
a + 2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [18]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

Стандартные математические функции, включенные в Python, не производят комплексные значения по умолчанию, так что они вряд ли случайно возникнут в вашем коде. Например: 

In [19]:
import math
math.sqrt(-1)

ValueError: math domain error

Если вы хотите получать в результате вычислений комплексные числа, то должны явно использовать cmath или соответствующим образом объявить это библиотекам, которые умеют с ними работать. Например: 

In [20]:
import cmath
cmath.sqrt(-1)

1j

# Pабота с бесконечными значениями и NaN 

Вам нужно создать или протестировать такие значения с плавающей точкой: бесконечность, минус бесконечность, NaN (not a number, «не число»). 

В Python нет специального синтаксиса для представления таких специальных значений с плавающей точкой, но они могут быть созданы с помощью float(). Например: 

In [1]:
a = float('inf')
b = float('-inf')
c = float('nan')

In [2]:
a

inf

In [3]:
b

-inf

In [4]:
c

nan

Чтобы проверить, не является ли значение таким, используйте функции math. isinf() и math.isnan(). Например:

In [7]:
import math
math.isinf(a)

True

In [8]:
math.isnan(c)

True

За подробностями об этих специальных значениях с плавающей точкой вы можете обратиться к спецификации IEEE 754. Однако здесь есть несколько хитрых деталей, о которых нужно знать. Особенное внимание нужно обратить на темы, связанные со сравнениями и операторами. Бесконечные значения распространяются в вычислениях согласно математическим правилам. Например: 

In [9]:
a = float('inf')

In [11]:
a + 45

inf

In [13]:
a * 10 

inf

In [15]:
10 / a

0.0

In [19]:
a / a

nan

In [20]:
a - a

nan

In [18]:
a + b

nan

Значения NaN распространяются через все операции, не возбуждая исключений. Например: 

In [22]:
c = float('nan')

In [24]:
c + 23

nan

In [26]:
c / 2

nan

In [28]:
c * 2

nan

In [29]:
math.sqrt(c)

nan

Тонкость с NaN заключается в том, что они никогда не будут равны друг другу. Например: 

In [31]:
d = float('nan')

In [33]:
c == d

False

In [34]:
c is d

False

In [35]:
c == c

False

In [36]:
c is c

True

По причине этого единственный безопасный способ проверить значение на NaN – это использовать math.isnan(), как показано в данном рецепте. Иногда программисты хотят изменить поведение Python таким образом, чтобы при возникновении в ходе вычислений бесконечностей или NaN возбуждались исключения. Для такого изменения поведения может быть использован модуль fpectl, но он не включен в стандартную поставку Python, является платформозависимым и на самом деле предназначен только для программистов-экспертов. За деталями обратитесь к онлайн-документации Python. 

#  Вычисления с дробями 

Модуль fractions может быть использован для выполнения математических операций с дробями. 

In [1]:
from fractions import Fraction

In [2]:
a = Fraction(5, 4)
b = Fraction(7, 16)

In [3]:
print(a + b)

27/16


In [4]:
print(a * b)

35/64


 Получение числителя/знаменателя 

In [6]:
c = a * b

In [7]:
c.numerator

35

In [8]:
c.denominator

64

Преобразуем в float 

In [9]:
float(c)

0.546875

Ограничиваем знаменатель значения 

In [10]:
print(c.limit_denominator(8))

4/7


Конвертируем float в дробь 

In [11]:
x = 3.75

In [12]:
y = Fraction(*x.as_integer_ratio())
y

Fraction(15, 4)

Вычисления с дробями нечасто возникают в обычных программах, но иногда имеет смысл ими воспользоваться. Например, если данные каких-то измерений поступают в виде дробей, то можно работать прямо с ними, что снимает необходимость конвертирования в десятичные дроби или числа с плавающей точкой

# Вычисления на больших массивах чисел

Вам нужно произвести вычисления на больших объемах числовых данных, таких как массивы или решетки. 

Для любых объемных вычислений с использованием массивов используйте библиотеку NumPy. Ее главное преимущество в том, что она предоставляет объект массива Python, который намного эффективнее и лучше подходит для математических вычислений, нежели стандартный список Python. Вот короткий пример, иллюстрирующий важные различия между обычными списками и массивами NumPy: 

In [1]:
#Списки Python
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [2]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [3]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
#массивы Numpy
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2

array([2, 4, 6, 8])

In [5]:
ax + 10

array([11, 12, 13, 14])

In [6]:
ax + ay

array([ 6,  8, 10, 12])

In [7]:
ax * ay

array([ 5, 12, 21, 32])

Как вы можете видеть, базовые математические операции с использованием массивов выполняются по-разному. Конкретно скалярные операции (например, ax * 2 или ax + 10) применяют операцию элемент за элементом. Также отметим, что выполнение таких математических операций, где каждый из операндов является массивом, применяет операцию ко всем элементам и создает новый массив. Тот факт, что математические операции применяются одновременно ко всем элементам, позволяет очень просто и быстро применить функции ко всему массиву. Например, если вы хотите вычислить значение многочлена: 

In [9]:
def f(x):
    return 3 * x ** 2 - 2 * x + 7

In [10]:
f(ax)

array([ 8, 15, 28, 47])

NumPy предоставляет набор «универсальных функций», которые также работают для операций над массивами. Они подменяют похожие функции, доступные в модуле math. Например: 

In [11]:
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [12]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Использование универсальных функций позволяет выполнить вычисление в сотни раз быстрее, чем проход по массиву и применение функций из math к каждому элементу. Так что используйте их при любой возможности. «Под капотом» массивы NumPy устроены похожим на массивы C или Fortran образом. А именно они представляют собой большие смежные области памяти, состоящие из однородных типов данных. Это дает возможность делать массивы намного более крупными, чем позволяет обычный список Python. Например, если вы хотите создать двумерную решетку размером 10 000×10 000 чисел с плавающей точкой, это не проблема: 

In [15]:
grid = np.zeros(shape=(10000, 10000), dtype=float)

In [16]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Все обычные операции все еще применяются к элементам одновременно:

In [17]:
grid += 10

In [18]:
grid

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

In [19]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ...,
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

Важнейший момент в использовании NumPy – это способ, которым она расширяет функциональность индексирования списков Python (особенно для многомерных массивов). Чтобы проиллюстрировать это, создадим простой двумерный массив и поэкспериментируем: 

In [22]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [23]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
#выбираем строку 1
a[1]

array([5, 6, 7, 8])

In [25]:
a[:, 1]

array([ 2,  6, 10])

In [26]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [27]:
a[1:3, 1:3] += 10

In [28]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [29]:
#транслируем строковый вектор на операции со всеми строками

In [30]:
a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 117, 119, 111],
       [109, 121, 123, 115]])

In [31]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [32]:
#условие присваивания в массиве
np.where(a<10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

NumPy – это основа огромного количества научных и инженерных библиотек для Python. Из широко используемых модулей он является одним из крупнейших  и сложных. При этом можно делать полезные вещи с помощью NumPy, начав экспериментировать с простыми примерами. Стоит отметить, что часто используется конструкция import numpy as np, как и показано в нашем примере. Это сокращает название, чтобы было удобно вводить его снова и снова в вашей программе. 

# Вычисления с матрицами и линейная алгебра

Вам нужно произвести матричные операции и операции линейной алгебры, такие как умножение матриц, поиск определителей, решение линейных уравнений. 

Библиотека NumPy содержит объект matrix. Матрицы – это нечто похожее на объекты массивов, но вычисления над ними следуют законам линейной алгебры. 

In [1]:
import numpy as np
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])

In [2]:
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [3]:
#возвращаем транспонированную матрицу
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [5]:
#возвращаем инвертированную матрицу(обратную матрицу)
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [6]:
#создаем вектор и умножаем
v = np.matrix([[2], [3], [4]])
v

matrix([[2],
        [3],
        [4]])

In [8]:
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [7]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

Другие операции можно найти в субпакете numpy.linalg

In [9]:
import numpy.linalg

In [10]:
#детерминант(определитель матрицы)
np.linalg.det(m)

-229.99999999999983

https://ru.wikipedia.org/wiki/%D0%9E%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C

In [11]:
#собственные значения
np.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

 Решение для x в mx = v 

In [12]:
x = np.linalg.solve(m, v)

In [13]:
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [14]:
m * x

matrix([[2.],
        [3.],
        [4.]])

In [15]:
v

matrix([[2],
        [3],
        [4]])

# Случайный выбор

Вы хотите выбрать случайные элементы из последовательности или сгенерировать случайные числа. 

Модуль random содержит разнообразные функции для генерации случайных чисел и выбора случайных элементов. Например, чтобы выбрать случайный элемент последовательности, используйте random.choice():


In [1]:
import random
values = [1, 2, 3, 4, 5, 6]

In [2]:
random.choice(values)

3

In [3]:
random.choice(values)

1

In [4]:
random.choice(values)

5

In [5]:
random.choice(values)

1

Чтобы получить выборку из N элементов, используйте random.sample(). Каждый элемент выбирается один раз, так что если значения в полученной выборке повторяются, то это разные элементы оригинальной последовательности, имеющие одинаковое значение:


In [6]:
random.sample(values, 2)

[3, 1]

In [7]:
random.sample(values, 3)

[6, 5, 3]

In [9]:
values1 = [1, 1, 1, 1, 2, 2]

In [10]:
random.sample(values1, 3)

[1, 2, 1]

Если вы хотите перемешать элементы в  последовательности, используйте random.shuffle():


In [12]:
random.shuffle(values)

In [13]:
values

[5, 4, 1, 6, 2, 3]

In [14]:
random.shuffle(values1)

In [15]:
values1

[1, 1, 1, 1, 2, 2]

In [18]:
random.shuffle(values1)

In [19]:
values1

[2, 1, 1, 1, 1, 2]

Чтобы сгенерировать случайные целые числа, используйте random.randint():


In [20]:
random.randint(0,10)

6

In [21]:
random.randint(0,10)

6

In [22]:
random.randint(0,10)

2

In [23]:
random.randint(0,10)

9

In [24]:
random.randint(0,10)

3

Чтобы сгенерировать одинаковые по формату числа с плавающей точкой в диапазоне от 0 до 1, используйте random.random():


In [25]:
random.random()

0.8288183556222442

In [26]:
random.random()

0.9737690378609322

Чтобы получить целое число из N случайных битов, используйте random. getrandbits():


In [27]:
random.getrandbits(200)

537405925934846407746196503452285928954492041949423278197494

In [28]:
random.getrandbits(2)

3

In [29]:
random.getrandbits(20)

836465

Модуль random вычисляет случайные числа, используя алгоритм «вихрь Мерсенна» (Mersenne twister, MT). Это детерминированный алгоритм, но вы можете изменить начальную инциализацию с помощью функции random.seed():


In [31]:
random.seed() #Инициализация на базе системного времени или os.urandom() 

In [34]:
import os
os.urandom(1)

b'\x94'

In [35]:
os.urandom(10)

b'\xdd\xd0\xe8k*r\rX\x05\x9d'

In [36]:
random.seed(12345) # Инициализация на базе заданного целого числа 

In [37]:
random.seed(b'bytedata') #Инициализация на базе байтовых данных

https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D1%85%D1%80%D1%8C_%D0%9C%D0%B5%D1%80%D1%81%D0%B5%D0%BD%D0%BD%D0%B0

Вдобавок к уже продемонстрированной функциональности random включает функции для равномерного, гауссова и других распределений вероятности. Например, random.uniform() вычисляет равномерно распределенные числа, а random. gauss() – нормально распределенные. За описанием других поддерживаемых распределений обратитесь к документации. 

In [38]:
random.uniform(0, 10)

9.211810322936035

In [39]:
random.uniform(0, 1) #матожидание -0, среднеквадратичное отклонение -1

0.22131028632891148

Функции в random не должны быть использованы в криптографических программах. Если вам нужна такая функциональность, обратитесь к функциям из модуля ssl. Например, ssl.RAND_bytes() может быть использована для генерации криптографически безопасных последовательностей случайных байтов.

In [40]:
import ssl
ssl.RAND_bytes(10)

b'3Q\xfaj\x98\xa4L\xe2\xb4\xb3'

# Перевод дней в секунды и другие базовые методы конвертации времени 

Вашей программе требуется производить простые преобразования времени, такие как выражение дней в секундах, часов в минутах и т. д. 

Чтобы производить конвертирование и арифметические операции над различными единицами времени, используйте модуль datetime. Например, чтобы представить интервал времени, создайте экземпляр timedelta: 

In [1]:
from datetime import timedelta

In [2]:
a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)

In [9]:
c = a + b

In [10]:
c

datetime.timedelta(days=2, seconds=37800)

In [4]:
c.days

2

In [5]:
c.seconds

37800

In [6]:
c.seconds/3600

10.5

In [8]:
c.total_seconds()/3600

58.5

total_seconds()
Return the total number of seconds contained in the duration. Equivalent to td / timedelta(seconds=1). For interval units other than seconds, use the division form directly (e.g. td / timedelta(microseconds=1)).

Note that for very large time intervals (greater than 270 years on most platforms) this method will lose microsecond accuracy.

Если вам нужно представить определенные даты и определенное время, создайте экземпляры datetime и проводите над ними обычные арифметические операции. Например: 

In [11]:
from datetime import datetime

In [13]:
a = datetime(2012, 9, 23)
print(a + timedelta(days=10))

2012-10-03 00:00:00


In [14]:
b = datetime(2012, 12, 21)
d = b - a
d.days

89

In [15]:
now = datetime.today()
print(now)

2019-11-13 10:21:50.242657


In [16]:
print(now + timedelta(minutes=10))

2019-11-13 10:31:50.242657


Стоит отметить, что datetime знает о существовании високосных годов. Например:

In [17]:
a = datetime(2012, 3, 1)
b = datetime(2012, 2, 28)
a - b

datetime.timedelta(days=2)

In [18]:
(a - b).days

2

In [19]:
c = datetime(2013, 3, 1)
d = datetime(2013, 2, 28)
(c - d).days

1

Для самых базовых операций над датой и временем модуля datetime достаточно. Если перед вами стоят более сложные задачи, такие как работа с временными зонами, нечеткими интервалами времени, подсчет дат выходных дней и т. д., посмотрите на модуль dateutil. Например, многие подобные вычисления над временем могут быть выполнены с помощью функции dateutil.relativedelta(). Одна важная возможность заключается в том, что она заполняет разрывы, которые возникают при работе с месяцами (и отличающимся количеством дней в них). Например: 

https://github.com/dateutil/dateutil

In [20]:
a = datetime(2012, 9, 23)
a + timedelta(months=1)

TypeError: 'months' is an invalid keyword argument for __new__()

In [22]:
from dateutil.relativedelta import relativedelta

In [23]:
a + relativedelta(months=+1)

datetime.datetime(2012, 10, 23, 0, 0)

In [24]:
a + relativedelta(months=+4)

datetime.datetime(2013, 1, 23, 0, 0)

In [26]:
# Время между двумя датами 
a = datetime(2012, 9, 23)
b = datetime(2012, 12, 21)
d = b - a
d

datetime.timedelta(days=89)

In [27]:
d = relativedelta(b, a) 
d

relativedelta(months=+2, days=+28)

In [28]:
d.months

2

In [29]:
d.days

28

# Определение даты последней пятницы

Вы хотите создать общее решение для поиска даты ближайшего прошедшего дня недели – например, последней прошедшей пятницы. 

В модуле datetime есть полезные функции и классы, которые помогают проводить такого рода вычисления. 

In [1]:
from datetime import datetime, timedelta

In [2]:
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

In [4]:
def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date
    
        

Использование этой функции в строке интерпретатора выглядит так:

In [5]:
datetime.today()

datetime.datetime(2019, 11, 14, 10, 27, 6, 405054)

In [6]:
get_previous_byday('Monday')

datetime.datetime(2019, 11, 11, 10, 27, 58, 721678)

In [7]:
get_previous_byday('Tuesday')

datetime.datetime(2019, 11, 12, 10, 28, 42, 917512)

In [8]:
get_previous_byday('Friday')

datetime.datetime(2019, 11, 8, 10, 29, 16, 142666)

In [9]:
get_previous_byday('Thursday')

datetime.datetime(2019, 11, 7, 10, 29, 39, 713391)

Необязательный параметр start_date может быть предоставлен с использованием другого экземпляра datetime. Например: 

In [10]:
get_previous_byday('Sunday', datetime(2020, 7, 12))

datetime.datetime(2020, 7, 5, 0, 0)

Этот рецепт работает путем отображения стартовой и интересующей даты на номера их позиций в неделе (где понедельник – это 0). Далее используется модульная арифметика, с ее помощью мы вычисляем, сколько дней назад была нужная дата. Потом нужная дата высчитывается от стартовой даты путем вычитания соответствующего экземпляра timedelta.

Если вы выполняете много подобных вычислений, рекомендуем установить пакет pythondateutil. Например, вот так можно выполнить аналогичную работу с использованием функции relativedata() из модуля dateutil: 

In [11]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.rrule import *
d = datetime.now()
print(d)

2019-11-14 10:35:02.050449


In [12]:
#следующая пятница
print(d + relativedelta(weekday=FR))

2019-11-15 10:35:02.050449


In [13]:
#последняя пятница
print(d + relativedelta(weekday=FR(-1)))

2019-11-08 10:35:02.050449


# Поиск диапазона дат для текущего месяца

У вас есть код, которому необходимо пройти в цикле по каждой дате текущего месяца, и вам нужен эффективный способ поиска диапазонов дат. 

Прохождение в цикле по датам не требует предварительного создания списка всех дат. Вы можете просто вычислить стартовую и конечную даты в диапазоне, а затем использовать объекты datetime.timedelta, инкрементируя дату. Вот функция, которая принимает любой объект datetime и возвращает кортеж, содержащий первую дату месяца и начальную дату следующего месяца: 

In [10]:
from datetime import datetime, date, timedelta
import calendar

In [11]:
def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
        _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
        end_date = start_date + timedelta(days=days_in_month)
        return(start_date, end_date)
        

In [12]:
a_day = timedelta(days=1)
first_day, last_day = get_month_range()
while first_day < last_day:
    print(first_day)
    first_day += a_day

2019-11-01
2019-11-02
2019-11-03
2019-11-04
2019-11-05
2019-11-06
2019-11-07
2019-11-08
2019-11-09
2019-11-10
2019-11-11
2019-11-12
2019-11-13
2019-11-14
2019-11-15
2019-11-16
2019-11-17
2019-11-18
2019-11-19
2019-11-20
2019-11-21
2019-11-22
2019-11-23
2019-11-24
2019-11-25
2019-11-26
2019-11-27
2019-11-28
2019-11-29
2019-11-30


Этот рецепт работает так: сначала вычисляется дата, соответствующая первому дню месяца. Быстрый способ сделать это – использовать метод replace() объектов date или datetime, чтобы присвоить атрибуту days значение 1. Приятно, что метод replace() создает объект того же типа, к которому он был применен. В данном случае, поскольку на входе у нас был экземпляр date, результат тоже является экземпляром date. Точно так же мы бы получили экземпляр datetime, если бы на входе у нас был экземпляр datetime. Затем функция calendar.monthrange() используется для нахождения количества дней в рассматриваемом месяце. Модуль calendar весьма полезен для получения базовых данных о календарях. Функция monthrange() возвращает кортеж, который содержит день недели и количество дней в месяце. Когда мы знаем количество дней в месяце, конечная дата вычисляется путем добавления соответствующего timedelta к стартовой дате. Тонкий, но важный аспект этого рецепта – конечная дата не включается в диапазон (на самом деле это первая дата следующего месяца). Это отражает присущее срезам и диапазонам Python поведение, которое также не подразумевает включение последнего элемента. Чтобы пройти в цикле по диапазону дат, используются стандартные математические операции и операторы сравнения. Например, экземпляр timedelta может быть использован для инкрементирования даты. Оператор < используется для проверки того, не достигнута ли конечная дата. В идеальном случае стоит создать функцию, которая будет работать как встроенная range(), но с датами. К счастью, есть чрезвычайно простой способ сделать это с помощью генератора:

In [13]:
def date_range(start, stop, step):
    while start < stop:
        yield start
        start +=step

In [14]:
for d in date_range(datetime(2012, 9, 1), datetime(2012, 10, 1), timedelta(hours=6)):
    print(d)

2012-09-01 00:00:00
2012-09-01 06:00:00
2012-09-01 12:00:00
2012-09-01 18:00:00
2012-09-02 00:00:00
2012-09-02 06:00:00
2012-09-02 12:00:00
2012-09-02 18:00:00
2012-09-03 00:00:00
2012-09-03 06:00:00
2012-09-03 12:00:00
2012-09-03 18:00:00
2012-09-04 00:00:00
2012-09-04 06:00:00
2012-09-04 12:00:00
2012-09-04 18:00:00
2012-09-05 00:00:00
2012-09-05 06:00:00
2012-09-05 12:00:00
2012-09-05 18:00:00
2012-09-06 00:00:00
2012-09-06 06:00:00
2012-09-06 12:00:00
2012-09-06 18:00:00
2012-09-07 00:00:00
2012-09-07 06:00:00
2012-09-07 12:00:00
2012-09-07 18:00:00
2012-09-08 00:00:00
2012-09-08 06:00:00
2012-09-08 12:00:00
2012-09-08 18:00:00
2012-09-09 00:00:00
2012-09-09 06:00:00
2012-09-09 12:00:00
2012-09-09 18:00:00
2012-09-10 00:00:00
2012-09-10 06:00:00
2012-09-10 12:00:00
2012-09-10 18:00:00
2012-09-11 00:00:00
2012-09-11 06:00:00
2012-09-11 12:00:00
2012-09-11 18:00:00
2012-09-12 00:00:00
2012-09-12 06:00:00
2012-09-12 12:00:00
2012-09-12 18:00:00
2012-09-13 00:00:00
2012-09-13 06:00:00


Повторимся, самое большое преимущество такой реализации в том, что датами и временем можно манипулировать с помощью стандартных математических операторов и операторов сравнения. 

# Конвертирование строк в даты и время 

https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

Ваше приложение получает данные о времени в строковом формате, но вы хотите конвертировать их в объекты datetime, чтобы выполнять над ними нестроковые операции. 

In [3]:
from datetime import datetime
text = '2012-09-20'
y = datetime.strptime(text, '%Y-%m-%d')
print('y = ', y)
z = datetime.now()
print('z = ', z)
diff = z - y
diff

y =  2012-09-20 00:00:00
z =  2019-11-18 10:35:44.656004


datetime.timedelta(days=2615, seconds=38144, microseconds=656004)

Метод datetime.strptime() поддерживает множество параметров форматирования, таких как %Y для года из четырех цифр и %m для месяца из двух цифр. Также стоит отметить, что эти параметры-заглушки работают в обратном направлении, что поможет, если вам нужно вывести объект datetime в строке и при этом заставить его красиво выглядеть. Предположим, что ваша программа генерирует объект datetime, но вам нужно создать из него красивую, понятную людям дату, чтобы потом вставить ее в заголовок автоматически создаваемого письма или отчета: 

In [4]:
nice_z = datetime.strftime(z, '%A %B %d, %Y')
nice_z

'Monday November 18, 2019'

Стоит отметить, что производительность метода strptime() часто оказывается намного хуже, чем вы могли бы ожидать, поскольку функция написана на чистом python и должна работать со всеми установками системной локализации. Если вы парсите множество дат в своей программе и знаете их точный формат, то можете добиться намного более высокой производительности путем написания собственного решения. Например, если вы знаете, что даты представлены в формате «YYYY-MM-DD», то можете написать такую функцию: 

In [8]:
from datetime import datetime
def parse_ymd(s):
    year_s, mon_s, day_s = s.split('-')
    return datetime(int(year_s), int(mon_s), int(day_s))

In [9]:
s = "2019-11-18"
parse_ymd(s)

datetime.datetime(2019, 11, 18, 0, 0)

При тестировании эта функции оказалась более чем в 7 раз быстрее метода datetime.strptime(). Это стоит держать в голове, если вы обрабатываете большие объемы данных с датами. 

# Манипулирование с датами с учетом временных зон

У вас назначена телефонная конференция на 21 декабря 2012 года в 9:30 утра в Чикаго. В какое местное время ваш друг из индийского города Бангалор должен выйти на связь? 

Для практически любых задач, связанных с временными зонами, вы можете использовать модуль pytz. Этот пакет предоставляет базу временных зон Олсона (tz databaze), которая является стандартом де-факто для многих языков программирования и операционных систем. 

Большая часть случаев использования pytz приходится на приведение к локальному времени дат, созданных с помощью библиотеки datetime. Например, вот как вы могли бы представить дату с чикагским местным временем: 

In [1]:
from datetime import datetime
from pytz import timezone
d = datetime(2012, 12, 21, 9, 30, 0)
print(d)

2012-12-21 09:30:00


In [3]:
# Локализуем дату для Чикаго 
central = timezone('US/Central') #метод pytz
loc_d = central.localize(d)
print('central =', central)
print('loc_d = ', loc_d)

central = US/Central
loc_d =  2012-12-21 09:30:00-06:00


Когда дата локализована, ее можно конвертировать в другие временные зоны. Чтобы найти бангалорское время, вы можете сделать так: 

In [4]:
# Преобразуем во время по Бангалору 
bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))
print('bang_d = ', bang_d)

bang_d =  2012-12-21 21:00:00+05:30


In [10]:
from pytz import all_timezones
#print(all_timezones)
# Локализуем дату  
d = datetime.now()
central = timezone('GB') #метод pytz
loc_d = central.localize(d)
print('central =', central)
print('loc_d = ', loc_d)
# Преобразуем во время по Москве 
msk_d = loc_d.astimezone(timezone('Europe/Moscow'))
print('msk_d = ', msk_d)

central = GB
loc_d =  2019-11-19 10:42:17.440662+00:00
msk_d =  2019-11-19 13:42:17.440662+03:00


Если вы собираетесь выполнять арифметические операции над локализованными датами, вам нужно знать о переводах времени с летнего на зимнее и прочих подобных деталях. Например, в 2013 году стандартное летнее время США началось 13 марта в 2:00 ночи по местному времени городов (время было переведено на час вперед). Если бы провели стандартную арифметическую операцию над датами, то получили бы неверный результат. Например: 

In [11]:
d = datetime(2013, 3, 10, 1, 45)
loc_d = central.localize(d)
print(loc_d)

2013-03-10 01:45:00+00:00


In [13]:
#неверный результат
from datetime import timedelta
later = loc_d + timedelta(minutes=30)
print('later = ', later)

later =  2013-03-10 02:15:00+00:00


Ответ получается неверным, поскольку он не учитывает перевод местного времени на один час. Чтобы исправить это, используйте метод временных зон normalize(). Например: 

In [14]:
from datetime import timedelta
later = central.normalize(loc_d + timedelta(minutes=30))
print('later = ', later)

later =  2013-03-10 02:15:00+00:00


Чтобы предотвратить взрыв головы, используйте обычную стратегию работы с локальным временем: преобразование всех дат в UTC и использование уже их для хранения и обработки. Например: 

In [17]:
import pytz
from pytz import utc
print('loc_d = ', loc_d)
utc_d = loc_d.astimezone(pytz.utc)
print('utc_d = ', utc_d)

loc_d =  2013-03-10 01:45:00+00:00
utc_d =  2013-03-10 01:45:00+00:00


Если время уже в UTC, вы можете не волноваться по поводу проблем, связанных с переходом на летнее время, а также прочих подобных вещах. Вы свободно можете выполнять арифметические операции с датами. Если же вы хотите вывести дату в локальном времени, просто сконвертируйте в нужную временную зону. Например: 

In [18]:
later_utc = utc_d + timedelta(minutes=30)
print(later_utc.astimezone(central))

2013-03-10 02:15:00+00:00


С использованием временных зон есть одна проблема: какие имена временных зон использовать? Например, в этом рецепте мы как­то узнали, что «Asia/ Kolkata» – это правильное название временной зоны для Индии. Чтобы узнать название нужной зоны, поищите в словаре pytz.country_timezones, указывая в качестве ключа код страны по ISO 3166. Например: 

In [19]:
pytz.country_timezones['IN']

['Asia/Kolkata']

К тому времени, как вы это прочтете, модуль pytz может быть признан устаревшим, а ему на смену придет улучшенная поддержка временных зон по PEP 4311. Однако многие из описанных проблем все равно нужно будет учитывать (вопросы работы с UTC и т. п.).


https://www.python.org/dev/peps/pep-0431/

https://pypi.org/project/pytz/